name: Continuous Deployment on GitHub Pages

on:
  push:
    branches:
      - 2023/website/main

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          npm ci

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - run: |
          npm ci
      - uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          angular_dist_build_folder: dist/jn-website-frontend
          deploy_branch: 2023/website/github/pages
          base_href: /archive/2023/website/

